FROM golang:alpine AS builder

WORKDIR /build

ADD go.mod .

COPY . .

RUN go build -o ./avito-tech ./cmd/main.go

FROM alpine

WORKDIR /build

COPY --from=builder /build/avito-tech /build/avito-tech
COPY --from=builder /build/.env .


CMD ["./avito-tech"]

